"""empty message

Revision ID: 807217afb855
Revises: 
Create Date: 2021-05-19 01:06:03.405105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807217afb855'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_log', sa.String(length=120), nullable=False),
    sa.Column('frase', sa.String(length=80), nullable=False),
    sa.Column('option_correcta', sa.String(length=80), nullable=False),
    sa.Column('option_mal1', sa.String(length=80), nullable=False),
    sa.Column('option_mal2', sa.String(length=80), nullable=False),
    sa.Column('option_mal3', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_log'),
    sa.UniqueConstraint('test_log')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=220), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('birthday', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_question', sa.Integer(), nullable=True),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_question'], ['question.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calificaciones')
    op.drop_table('user')
    op.drop_table('question')
    # ### end Alembic commands ###
